<?php

return 
[
	/*
    |--------------------------------------------------------------------------
    | Sandbox
    |--------------------------------------------------------------------------
    |
    | This is a flag notfies the API that we are in sanbox mode and use the sanbox API endpoints 
    |
    | Default: true
    |
    */

	"sandbox" : true,

	/*
    |--------------------------------------------------------------------------
    | Paybill Number
    |--------------------------------------------------------------------------
    |
    | This is a registered Paybill Number that will be used as the Merchant ID
    | on every transaction. This is also the account to be debited.
    |
    | Sandbox PAYBILL NUMBER: 898998
    |
    */

    'paybill_number' => 898998,

    /*
    |--------------------------------------------------------------------------
    | Consumer Key
    |--------------------------------------------------------------------------
    |
    | OAuth Key generated on developer.safaricom.com after your created app is approved
    |
    */

    "consumer_key" => env('consumer_key'),

    /*
    |--------------------------------------------------------------------------
    | Consumer Secret
    |--------------------------------------------------------------------------
    |
    | OAuth Secret generated on developer.safaricom.com after your created app is approved
    |
    */

    "consumer_secret" => env('consumer_secret'),

    /*
    |--------------------------------------------------------------------------
    | Access Token
    |--------------------------------------------------------------------------
    |
    | OAuth 2.0 Access Token generated by the package or you using the developer.safaricom.com portal
    |
    */

    "access_token" => env('access_token'),

    /*
    |--------------------------------------------------------------------------
    | B2C Resource URL
    |--------------------------------------------------------------------------
    |
    | This API enables Business to Customer (B2C) transactions between a company and customers who are the
    | end-users of its products or services. Use of this API requires a valid and verified B2C M-Pesa Short code.
    |
    */

    "B2C_resource_url" => "https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest",

    /*
    |--------------------------------------------------------------------------
    | B2B Resource URL
    |--------------------------------------------------------------------------
    |
    | This API enables Business to Business (B2B) transactions between a business and another business.
    | Use of this API requires a valid and verified B2B M-Pesa short code for the business initiating the transaction 
    | and both businesses involved in the transaction.
    |
    */

    "B2B_resource_url" => "https://sandbox.safaricom.co.ke/mpesa/b2b/v1/paymentrequest",

    /*
    |--------------------------------------------------------------------------
    | C2B Register Resource URL
    |--------------------------------------------------------------------------
    |
    | The C2B Register URL API registers the 3rd party’s confirmation and validation URLs to M-Pesa ; which then maps these URLs to the
    | 3rd party shortcode. Whenever M-Pesa receives a transaction on the shortcode, M-Pesa triggers a validation request against the 
    | validation url and the 3rd party system reponds to M-Pesa with a validation response (either a success or an error code). 
    | The response expected is The success code the 3rd party

	| M-Pesa completes or cancels the transaction depending on the validation response it receives from the 3rd party system. 
	| A confirmation request of the transaction is then sent by M-Pesa through the confirmation URL back to the 3rd party which then
	| should respond with a success acknowledging the confirmation.
    |
    */

    "C2B_register_url" => "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl",

    /*
    |--------------------------------------------------------------------------
    | C2B Simulate Transaction Resource URL
    |--------------------------------------------------------------------------
    |
    | Simulate C2B Paybill and Buy Goods transactions
    |
    */

    "C2B_simulate_transaction_url" => "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate"

    /*
    |--------------------------------------------------------------------------
    | Account Balance Resource URL
    |--------------------------------------------------------------------------
    |
    | The Account Balance API requests for the account balance of a shortcode.
    |
    */

    "account_balance_url" => "https://sandbox.safaricom.co.ke/mpesa/accountbalance/v1/query",

    /*
    |--------------------------------------------------------------------------
    | Reversal Resource URL
    |--------------------------------------------------------------------------
    |
    | Reverses a B2B, B2C or C2B M-Pesa transaction.
    |
    */

    "reversal_url" => "https://sandbox.safaricom.co.ke/mpesa/reversal/v1/request",

    /*
    |--------------------------------------------------------------------------
    | STK Push Query Resource URL
    |--------------------------------------------------------------------------
    |
    | 
    |
    */

    "STK_push_query_url" => "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest",

     /*
    |--------------------------------------------------------------------------
    | STK Push Query Request Resource URL
    |--------------------------------------------------------------------------
    |
    | 
    |
    */

    "STK_push_query_request_url" => "https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query",

    /*
    |--------------------------------------------------------------------------
    | Transaction Status Resource URL
    |--------------------------------------------------------------------------
    |
    | Transaction Status API checks the status of a B2B, B2C and C2B APIs transactions.
    |
    */

    "transaction_status_url" => "https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query",

    /*
    |--------------------------------------------------------------------------
    | Check Identity Resource URL
    |--------------------------------------------------------------------------
    |
    | The Check Identity API is used to verify ownership of a MSSISDN/Phone number.
    |
    */

    "check_identity_url" => "https://sandbox.safaricom.co.ke/mpesa/checkidentity/v1/query",

    /*
    |--------------------------------------------------------------------------
    | Credit Score Onboarding Resource URL
    |--------------------------------------------------------------------------
    |
    | The credit score onboarding API is used by Safaricom partners to subscribe to the credit score 
    | service so that they can use the credit score customer and credit score merchant APIs. 
    | Partners requesting to subscribe to the credit score service are vetted and agree to Safaricom’s Credit Score Terms of Use.
    |
    */

    "credit_score_onboarding_url" => "http://sandbox.safaricom.co.ke/mpesa/creditScore/v1/subscribe",

    /*
    |--------------------------------------------------------------------------
    | Credit Score Subscription Resource URL
    |--------------------------------------------------------------------------
    |
    | The credit score subcription API is used to subscribe and/or unsubscribe a Safaricom’s (individual) 
    | customer or M-Pesa Merchant for credit score service.
    |
    */

    "credit_score_subscription_url" => "http://sandbox.safaricom.co.ke/mpesa/creditScore/v1/subscribe",

    /*
    |--------------------------------------------------------------------------
    | Customer Credit Score Resource URL
    |--------------------------------------------------------------------------
    |
    | This API takes in a customer’s mobile number and returns a set of data attributes reflecting usage of 
    | Safaricom M-PESA and GSM services. As required for all the data APIs, customers must have consented to 
    | the partner to access their data before access is allowed.
    |
    */

    "customer_credit_score_url" => "https://sandbox.safaricom.co.ke/mpesa/creditScore/v1/customer",

    /*
    |--------------------------------------------------------------------------
    | Merchant Credit Score Resource URL
    |--------------------------------------------------------------------------
    |
    | This API takes in the merchant’s Buygoods Store Number or Paybill number and returns a set of data attributes 
    | reflecting payments and transactions history as seen from M-PESA. The more a merchant uses M-PESA for collection (receipts)
    | and disbursements (payments out) the richer the data available.
	| The merchant must have consented to the partner for their data to be accessed via this API.
    |
    */

    "merchant_credit_score_url" => "https://sandbox.safaricom.co.ke/mpesa/creditScore/v1/merchant",

    /*
    |--------------------------------------------------------------------------
    | Agent Score (Coming soon) Resource URL
    |--------------------------------------------------------------------------
    |
    | This API takes in the agents Store Number and returns a set of data attributes reflecting commissions and transaction 
    | history as seen from M-PESA.
	| The agent must have consented to the partner for their data to be accessed via this API.
    |
    */

    "agent_score_url" => ""
]